build_root:
  project_image:
    dockerfile_path: .ci/openshift-ci/build-root/Dockerfile
releases:
  latest: # required; a dependency of the workflow to provide "release:latest"
    release:
      channel: stable
      version: "4.12"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: intersmash-e2e
  steps:
    cluster_profile: aws-2 # required; the cluster profile to create the cloud resources for the hosted cluster by HyperShift
    env:
      HYPERSHIFT_HC_RELEASE_IMAGE: quay.io/openshift-release-dev/ocp-release:4.12.9-multi # optional; the payload to install
    test:
    - as: intersmash-build
      commands: |
        ls -la .ci/openshift-ci/build-root/
        /bin/bash .ci/openshift-ci/build-root/e2e-test.sh
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: hypershift-hostedcluster-workflow
zz_generated_metadata:
  branch: main
  org: Intersmash
  repo: intersmash
